version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/'
      - '/api'
      - '/sdk/core'
      - '/sdk/cli'
      - '/sdk/http'
      - '/sdk/evals'
      - '/sdk/credentials'
      - '/sdk/llm'
      - '/test_workflows'
    schedule:
      interval: weekly
    open-pull-requests-limit: 25
    groups:
      patch-updates:
        update-types: ['patch']
        applies-to: 'version-updates'
      dev-updates:
        update-types: ['minor']
        applies-to: 'version-updates'
