version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 25
    groups:
      babel:
        patterns: ['@babel/*']
        applies-to: 'version-updates'
      oclif:
        patterns: ['oclif', '@oclif/*']
        applies-to: 'version-updates'
      minor-updates:
        update-types: ['patch', 'minor']
        exclude-patterns: ['@babel/*', 'oclif', '@oclif/*']
        applies-to: 'version-updates'
    cooldown:
      default-days: 3
