import { describe, it, expect } from 'vitest';
import { getProviderNames } from '../ai_provider.js';
import snapshot from './models_pricing_snapshot.json' with { type: 'json' };

/* Guards the committed snapshot, which is regenerated by scripts/take_models_pricing_snapshot.js. */
describe( 'models pricing snapshot', () => {
  it( 'covers every provider shipped by the package', () => {
    const providerIds = Object.keys( snapshot ).filter( key => key !== '_meta' );

    expect( providerIds.sort() ).toEqual( getProviderNames().sort() );
  } );

  it.each( getProviderNames() )( 'prices at least one %s model', providerId => {
    const priced = Object.values( snapshot[providerId]?.models ?? {} ).filter( model => model.cost );

    expect( priced.length ).toBeGreaterThan( 0 );
  } );
} );
