import { afterEach, describe, expect, it } from 'vitest';
import resolveInvocationDir from './resolve_invocation_dir';

const OriginalError = Error;

describe( 'Resolve Invocation Dir', () => {
  afterEach( () => {
    Error = OriginalError;
  } );

  it( 'Should detect the invocation dir from the tests workflow', () => {
    const stack = `Error
    at resolveInvocationDir (file:///app/sdk/core/src/utils/resolve_invocation_dir.js)
    at fn (file:///app/test_workflows/dist/simple/steps.js:8:21)
    at wrapper (file:///app/sdk/core/src/interface/step.js:12:26)
    at executeNextHandler (/app/node_modules/@temporalio/worker/lib/activity.js:99:54)
    at Storage.runWithContext.parentId (file:///app/sdk/core/src/worker/interceptors/activity.js:31:63)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_context_frame:63:14)
    at Object.runWithContext (file:///app/sdk/core/src/async_storage.js:12:44)
    at ActivityExecutionInterceptor.execute (file:///app/sdk/core/src/worker/interceptors/activity.js:31:36)
    at next (/app/node_modules/@temporalio/common/lib/interceptors.js:22:51)
    at Activity.execute (/app/node_modules/@temporalio/worker/lib/activity.js:101:26)
    at /app/node_modules/@temporalio/worker/lib/activity.js:149:29`;

    Error = class extends OriginalError {
      constructor( ...args ) {
        super( ...args );
        this.stack = stack;
      }
    };

    expect( resolveInvocationDir() ).toBe( '/app/test_workflows/dist/simple' );
  } );

  it( 'Should detect the invocation dir from the sandbox environment at sdk/core', () => {
    const stack = `Error
    at resolveInvocationDir (file:///app/sdk/core/src/utils/resolve_invocation_dir.js)
    at workflow (file:///app/sdk/core/src/interface/workflow.js:25:16)
    at file:///app/test_workflows/dist/nested/workflow.js:4:16
    at ModuleJob.run (node:internal/modules/esm/module_job:365:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async importComponents (file:///app/sdk/core/src/worker/loader_tools.js:54:22)
    at async loadWorkflows (file:///app/sdk/core/src/worker/loader.js:64:38)
    at async file:///app/sdk/core/src/worker/index.js:21:21`;

    Error = class extends OriginalError {
      constructor( ...args ) {
        super( ...args );
        this.stack = stack;
      }
    };

    expect( resolveInvocationDir() ).toBe( '/app/test_workflows/dist/nested' );
  } );

  it( 'Should detect the invocation dir from workflow loading at core', () => {
    const stack = `Error
    at __WEBPACK_DEFAULT_EXPORT__ (/app/sdk/core/src/utils/resolve_invocation_dir.js:13:0)
    at workflow (/app/sdk/core/src/interface/workflow.js:22:43)
    at ../../test_workflows/dist/nested/workflow.js (/app/test_workflows/dist/nested/workflow.js:4:24)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at ./src/worker/temp/__workflows_entrypoint.js (null:null:null)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at importWorkflows (/app/sdk/core/src/worker/temp/__workflows_entrypoint-autogenerated-entrypoint.cjs:9:9)
    at Object.initRuntime (/app/node_modules/@temporalio/workflow/src/worker-interface.ts:78:16)
    at __TEMPORAL_CALL_INTO_SCOPE (evalmachine.<anonymous>:30:40)
    at evalmachine.<anonymous>:1:1`;

    Error = class extends OriginalError {
      constructor( ...args ) {
        super( ...args );
        this.stack = stack;
      }
    };

    expect( resolveInvocationDir() ).toBe( '/app/test_workflows/dist/nested' );
  } );

  it( 'Should detect the invocation dir from a workflow using core installed via NPM', () => {
    const stack = `Error
    at resolveInvocationDir (file:///app/node_modules/@outputai/core/src/utils/resolve_invocation_dir.js)
    at fn (file:///app/dist/simple/steps.js:8:21)
    at wrapper (file:///app/node_modules/@outputai/core/src/interface/step.js:12:26)
    at executeNextHandler (/app/node_modules/@temporalio/worker/lib/activity.js:99:54)
    at Storage.runWithContext.parentId (file:///app/node_modules/@outputai/core/src/worker/interceptors/activity.js:31:63)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_context_frame:63:14)
    at Object.runWithContext (file:///app/node_modules/@outputai/core/src/async_storage.js:12:44)
    at ActivityExecutionInterceptor.execute (file:///app/node_modules/@outputai/core/src/worker/interceptors/activity.js:31:36)
    at next (/app/node_modules/@temporalio/common/lib/interceptors.js:22:51)
    at Activity.execute (/app/node_modules/@temporalio/worker/lib/activity.js:101:26)
    at /app/node_modules/@temporalio/worker/lib/activity.js:149:29`;

    Error = class extends OriginalError {
      constructor( ...args ) {
        super( ...args );
        this.stack = stack;
      }
    };

    expect( resolveInvocationDir() ).toBe( '/app/dist/simple' );
  } );
} );
