#!/usr/bin/env node

console.log( '\n────────────────────────────────────────────\n' );
console.log( '\x1b[33;1mBREAKING CHANGES in @outputai/cli\n\x1b[0m' );
console.log( 'NPM scripts generated by @outputai/cli changed in version \x1b[4m0.1.11\x1b[0m.' );
console.log( 'Projects initialized on older versions may not start correctly in local dev mode' );
console.log( 'Run \`\x1b[35;3mnpx output reconfigure\x1b[0m\` to reconcile the package.json.\x1b[0m\n' );
console.log( '────────────────────────────────────────────\n' );
