name: Publish API Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    name: Publish API Docker Image
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish API Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: ./ops/publish_api_image.sh
