name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  main:
    name: Publish NPM Packages
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    container:
      image: node:24.13.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable pnpm
        run: corepack enable

      - name: Validate
        run: ./ops/validate.sh

      - name: Publish
        run: ./ops/publish_npm_prod.sh
