name: Dependabot Validation
on:
  pull_request_target:
    branches:
      - main

jobs:
  main:
    name: Validate
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    container:
      image: node:24.13.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable pnpm
        run: corepack enable

      - name: Validate
        run: ./ops/validate.sh
